server:
  port: 8080

spring:
  redis:
    host: xxx.xxx.xxx.xxx
    port: 6379
    password: xxxxxx

# 方法缓存
methodcache:
  # 启用。true：开启，false：关闭，默认false
  enable: true
  # 输出日志(info级别)。true：开启，false：关闭，默认false
  enable-log: true
  # 缓存方式。(M)emory：内存，(R)edis：redis方式，默认M
  cache-type: R
