server:
  port: 8080

spring:
  application:
    name: demo-for-methodcache
  redis:
    database: 1
    host: 127.0.0.1
    port: 6378

# 方法缓存
methodcache:
  # 缓存名称，若不设置则取 ${spring.application.name}
  name: demo-for-methodcache-with-redis
  # 启用。true：开启，false：关闭，默认false
  enable: true
  # 输出日志(info级别)。true：开启，false：关闭，默认false
  enable-log: true
  # 缓存方式。(M)emory：内存，(R)edis：redis，默认M
  cache-type: R
  # 端点信息，默认关闭
  enable-endpoint: true
  # 统计，默认关闭
  enable-statistics: true
